name: coffee-news # you probably want to 'snapcraft register <name>'
version: '1.0.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Keep up-to-date with news and weather with Coffee # 79 char long summary
description: |
  Get the latest news and weather information with Coffee, keep up-to-date with the local weather information and news from a variety of sources

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  coffee:
    command: com.github.nick92.coffee
    desktop: usr/share/applications/com.github.nick92.coffee.desktop
    environment:
     GSETTINGS_SCHEMA_DIR: $SNAP/share/glib-2.0/schemas

parts:
  coffee:
    source: https://github.com/nick92/coffee.git
    plugin: meson
    meson-parameters: [--prefix=/usr]
    source-type: git
    build-packages:
     - libgtk-3-dev
     - valac
     - libglib2.0-dev
     - libjson-glib-dev
     - libsoup2.4-dev
     - libwebkit2gtk-4.0-dev
     - libgee-0.8-dev
     - libgeocode-glib-dev
     - libgeoclue-2-dev